# BASED ON smarthomebeginner.com
########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
 
include:
  ########################### SERVICES
 
  # CORE
  - socket-proxy.yml
  - portainer.yml
  # DOWNLOADERS
  #- sabnzbd.yml
  - gluetun.yml
  - qbittorrent.yml
  - transmission.yml
  - flaresolverr.yml
  - prowlarr.yml
  # PVRS
  - radarr.yml
  - sonarr.yml
  - bazarr.yml
  # EXTRA
  - tautulli.yml
  - overseerr.yml
  - list-sync.yml
  - flexget.yml
