services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports: #make sure to include these for qbittorrent to work
      # qbittorrent 
      - 8081:8080
      - 6881:6881
      - 6881:6881/udp
      # transmission
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESSES=
      - SERVER_COUNTRIES=
    volumes:
      - $DOCKERDIR/appdata/gluetun:/gluetun
    restart: unless-stopped
