services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
	security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["media", "arrs", "all"]
    networks:
      - default
    volumes:
      - $DOCKERDIR/appdata/overseerr:/config
    ports:
      - 5055:5055
	environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
