services:
  requestrr:
    image: thomst08/requestrr
    container_name: requestrr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["media", "arrs", "all"]
    networks:
      - default
    ports:
      - "4545:4545"
    volumes:
      - $DOCKERDIR/appdata/requestrr:/root/config
      # - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      # PUID: $PUID
      # PGID: $PGID
